services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user